Scrap bugs rarity
SawyerHood/animal-crossing-catch pull request #20
Opened 2020-05-15 09:18 UTC by erwanlbp

In response to #6

I did just the bugs for a start, if it's accepted I'll try the other ones.

To scrap the rarity we need to go on every bug page so it takes longer to scrap.

The PR for sure needs a bit of rework, it was to start the thing. So please comment :)

2020-05-18 00:55 UTC, SawyerHood commented on scraper/scraper.js
> +      if (rarity.includes("Common")) {
I'm fine with keeping these values as either the names they are now or a number value between 1 -> 5. When displaying these we are probably just going to show either the text or if we are fancy a few star icons. I think we should start with just the words

2020-05-18 00:56 UTC, SawyerHood commented
Thanks for taking this on. We might want to make the scraping a little more efficient. This is going to make it hit 100s of pages (if we enable it for fish as well). If we do this we will probably want to run multiple pages at once (this work can be done in parallel). I think we should rework this to do that before I merge in. Let me know if you need any help!

2020-05-18 01:15 UTC, SawyerHood requested changes
See above ^ I forgot to request changes

2020-05-18 08:32 UTC, erwanlbp commented
> Thanks for taking this on. We might want to make the scraping a little more efficient. This is going to make it hit 100s of pages (if we enable it for fish as well). If we do this we will probably want to run multiple pages at once (this work can be done in parallel). I think we should rework this to do that before I merge in. Let me know if you need any help!

I changed it to run in parallel, but loading 80+ tabs in parallel take some times :joy: 
So I changed it to run by chunks, 4 chunks of the bugs array in parallel.
I timed :
- 45s for 4 parallel chunks
- more than 50s for 2 chunks
- around 52s for 3 chunks
- around 46s for the sequential

My machine is not a beast and I'm not equipped with fiber.

What do you think ?

2020-05-23 01:47 UTC, SawyerHood approved these changes
Sorry I've been busy with work! This looks like a good starting point. In the future we might want to find a better data source for all of the data (I actually was able to rip all of the assets straight from the game on my computer) so we don't have to wait so long to scrape everything. This looks awesome!

2020-05-23 01:47 UTC, SawyerHood commented on scraper/scraper.js
> +    console.log(`[${arrayStart},${arrayEnd}] [${i}] Scrap bug rarity ${bug.name}`);
This should be "scrape" not scrap

2020-05-23 01:48 UTC, merged